apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
spec:
  project: default
  sources:
    - repoURL: public.ecr.aws/karpenter
      chart: karpenter
      targetRevision: "1.14.0"
      helm:
        values: |
          replicas: 1
          logLevel: debug 
          settings:
            clusterName: platform-lab
          serviceAccount:
            create: true
            name: karpenter
          controller:
            resources:
              requests:
                cpu: 250m
                memory: 256Mi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-type
                        operator: In
                        values:
                          - system

          tolerations:
            - key: node-type
              operator: Equal
              value: system
              effect: NoSchedule
    - repoURL: git@github.com:thisiscaetano/platform-lab.git
      path: platform-lab-global-manifest/apps/karpenter/base
      targetRevision: HEAD
  destination:
    name: lab
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true