apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: spot
spec:
  amiFamily: AL2023
  instanceProfile: "KarpenterProfile"

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: platform-lab
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: platform-lab
  amiSelectorTerms:
    - alias: al2023@latest

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true

  tags:
    Name: karpenter-platform-lab-spot
    karpenter.sh/discovery: platform-lab
    Environment: prd