apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
spec:
  project: default
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.122.0
    helm:
      releaseName: opentelemetry-operator
      values: |
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi

  destination:
    namespace: obs
    name: lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
