apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:

#- apps/karpenter/base/application.yaml
- apps/external-secrets/overlays/production/application.yaml
- apps/istio/overlays/prd/application.yml
- apps/web-app/overlays/prd/application.yaml
- apps/stakater-reloader/overlays/production/application.yaml
- apps/otel/application.yaml
- apps/prometheus/overlays/prd/application.yaml