apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: hello-gitops-instrumentation
spec:
  exporter:
    # endpoint do seu OTel Collector (ajuste para o service dele)
    endpoint: http://otel-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  python:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
