apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- instrumentation.yaml
- serviceaccount.yaml
- externalsecret.yaml
- deployment.yaml
- service.yaml

images:
- name: image-set
  newName: 017820664539.dkr.ecr.us-east-1.amazonaws.com/hello-gitops
  newTag: dc826cc
