apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- instrumentation.yaml
- serviceaccount.yaml
- externalsecret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

configMapGenerator:
- files:
  - dashboard.json
  name: hello-gitops-dashboard
  options:
    disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"
 
images:
- name: image-set
  newName: 017820664539.dkr.ecr.us-east-1.amazonaws.com/hello-gitops
  newTag: 050164e
