apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - instrumentation.yaml
  - serviceaccount.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml

images:
- name: image-set
  newName: 
  newTag: 