apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 88.6.1
      helm:
        releaseName: kube-prometheus-stack
        values: |
          crds:
            enabled: false
          grafana:
            enabled: true
            additionalDataSources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki-gateway.obs.svc.cluster.local
                isDefault: false
                jsonData:
                  maxLines: 1000
            sidecar:
              dashboards:
                enabled: true
                label: grafana_dashboard
                labelValue: "1"
                searchNamespace: ALL
          prometheus:
            prometheusSpec:
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 512Mi
    - repoURL: git@github.com:thisiscaetano/platform-lab.git
      targetRevision: HEAD
      path: platform-lab-global-manifest/apps/prometheus/overlays/prd/dashboard
      
    - repoURL: git@github.com:thisiscaetano/platform-lab.git
      targetRevision: HEAD
      path: platform-lab-global-manifest/apps/prometheus/overlays/prd
  destination:
    name: lab
    namespace: obs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    targetRevision: 31.0.1
  destination:
    name: lab
    namespace: obs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true