apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater
spec:
  project: default
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.2.16
    helm:
      releaseName: stakater
      values: |
        reloader:
          ignoreConfigMaps: false 
          deployment: 
            resources:
              limits:
                cpu: 50m
                memory: 64Mi
              requests:
                cpu: 25m
                memory: 32Mi

  destination:
    namespace: stakater
    name: lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
