apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-claims
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:thisiscaetano/platform-lab.git
    targetRevision: HEAD
    path: platform-lab-global-manifest/apps/crossplane/claims/overlays/prd
  destination:
    name: lab
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
