apiVersion: dns.upjet-cloudflare.upbound.io/v1alpha1
kind: Record
metadata:
  name: istio-ingressgateway-lab
  namespace: upbound-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  forProvider:
    name: istio-ingressgateway-lab
    type: CNAME
    content: "a3e2861b28f5e4257b2687544ccf9fc4-285860955.us-east-1.elb.amazonaws.com"
    comment: "DNS record for istio-ingressgateway environment lab"
    proxied: true
    ttl: 1
    zoneId: "83ea4522d0e2006fcf523a2853f23c47"
  providerConfigRef:
    name: cloudflare-provider-config
---
apiVersion: dns.upjet-cloudflare.upbound.io/v1alpha1
kind: Record
metadata:
  name: argocd-lab
  namespace: upbound-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  forProvider:
    name: argocd
    type: CNAME
    content: "istio-ingressgateway-lab.paulojuniorsre.com.br"
    comment: "DNS record for argocd environment lab"
    proxied: true
    ttl: 1
    zoneId: "83ea4522d0e2006fcf523a2853f23c47"
  providerConfigRef:
    name: cloudflare-provider-config
---
apiVersion: dns.upjet-cloudflare.upbound.io/v1alpha1
kind: Record
metadata:
  name: grafana-lab
  namespace: upbound-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  forProvider:
    name: grafana
    type: CNAME
    content: "istio-ingressgateway-lab.paulojuniorsre.com.br"
    comment: "DNS record for grafana environment lab"
    proxied: true
    ttl: 1
    zoneId: "83ea4522d0e2006fcf523a2853f23c47"
  providerConfigRef:
    name: cloudflare-provider-config
---
apiVersion: dns.upjet-cloudflare.upbound.io/v1alpha1
kind: Record
metadata:
  name: web-app-lab
  namespace: upbound-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  forProvider:
    name: app
    type: CNAME
    content: "istio-ingressgateway-lab.paulojuniorsre.com.br"
    comment: "DNS record for web app environment lab"
    proxied: true
    ttl: 1
    zoneId: "83ea4522d0e2006fcf523a2853f23c47"
  providerConfigRef:
    name: cloudflare-provider-config
