apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:thisiscaetano/platform-lab.git
      targetRevision: HEAD
      path: platform-lab-global-manifest/apps/argocd/
  destination:
    name: lab
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true